### ISSUE TITLE
Ventura Help

### ISSUE THREAD

**Issue by IrvingGuerra** [mavethee/Hackintosh-OpenCore-EFI-HP-Z420#5]
Hey! 
What i have to do if i want to install Ventura but with a RX6600? Its a supported gpu

With Monterey i dont have any trouble...

![Captura de Pantalla 2023-04-13 a la(s) 23 20 03](https://user-images.githubusercontent.com/37481550/231948114-98239e02-7b4e-4dff-b265-b92be569ebcc.png)

I follow the Notes for Monterey, but with Ventura, its not booting.

Thanks!

**Comment by mavethee** [comment]
Hey,

At start, [I'm not writting so complex READMEs to skip it](https://github.com/mavethee/Hackintosh-OpenCore-EFI-HP-Z420#what-has-been-done-and-must-be-done-to-make-it-boot), that's literally first paragraph.

Ventura installer won't boot for whatever reason on MacPro6,1 and not sure how to skip all those checks in installer just like on already installed system that's why I provide two versions of EFI. Post-Install can be 

That's on OCLP to "fix it" by getting rid of AVX2 from AMD stack drivers, newer than Polaris/Vega won't work on pre-AVX2 CPUs. [They are aware, that's in works, no ETAs]

<img width="851" alt="CleanShot 2023-04-14 at 13 24 16@2x" src="https://user-images.githubusercontent.com/47083527/232031374-70bff442-05e5-4571-9d3d-e55a93ab3557.png">

if my docs aren't enough, [check OCLP's guide](https://dortania.github.io/OpenCore-Legacy-Patcher/VENTURA-DROP.html#currently-unsupported-broken-hardware-in-ventura) and as always issues with Hacks running OCLP'd macOS is on your own thing.

For now, reset all the things "for OCLP" and stay on Monterey as it's still supported macOS and Ventura is quite bugged anyways or if you have spare Legacy Metal/Polaris/Vega dGPU laying around and want waste your money for time being just to run Ventura, then you can try installing it.

As I keep sorta daily drive it, I will do my best to keep it alive but again for now, it's quite limited.

Happy Hackintoshing and more READING before actually doing something,
mavethee
